# Generated by Django 3.2 on 2021-07-27 10:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_asesor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asesorA', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.IntegerField(unique=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesorEmp', to='nucleo.asesor')),
            ],
        ),
        migrations.CreateModel(
            name='nomYSs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominas', models.BooleanField(default=False)),
                ('rlcRnt', models.BooleanField(default=False)),
                ('cra', models.BooleanField(default=False)),
                ('mes', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresaNom', to='nucleo.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='modelo111190',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseIRPF', models.FloatField()),
                ('rent', models.FloatField()),
                ('presentado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa111', to='nucleo.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_vencimiento', models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('BAJA', 'Baja'), ('BAJA 51', 'Baja51'), ('BAJA 93', 'Baja93'), ('BAJA 85', 'Baja85'), ('BAJA 91', 'Baja91'), ('BAJA 53', 'Baja53'), ('BAJA 94', 'Baja94'), ('BAJA 54', 'Baja54'), ('REDUCCIÓN DE JORNADA', 'Reduccion Jornada'), ('AMPLIACIÓN DE JORNADA', 'Ampliacion Jornada'), ('INACTIVIDAD', 'Inactividad'), ('TRANSFORMACIÓN', 'Transformacion'), ('PROROGA', 'Prorroga'), ('DESAFECTACIÓN', 'Desafectacion'), ('LLAMAMIENTO', 'Llamamiento'), ('BAJA Y ALTA', 'Baja Y Alta')], default='BAJA', max_length=25)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('segSocial', models.BooleanField(default=False)),
                ('sepe', models.BooleanField(default=False)),
                ('enviadoContrato', models.BooleanField(default=False)),
                ('sage', models.BooleanField(default=False)),
                ('certificadoEmpresa', models.BooleanField(default=False)),
                ('envioLiquidacion', models.BooleanField(default=False)),
                ('firmaFY', models.BooleanField(default=False)),
                ('fin', models.BooleanField(default=False)),
                ('oculto', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresaEmp', to='nucleo.empresa', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
