# Generated by Django 3.2 on 2021-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_auto_20210802_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo111190',
            name='base190',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='modelo111190',
            name='reten190',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
