# Generated by Django 3.2 on 2021-08-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_auto_20210802_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo111190',
            name='bases111',
        ),
        migrations.RemoveField(
            model_name='modelo111190',
            name='difBase',
        ),
        migrations.RemoveField(
            model_name='modelo111190',
            name='difReten',
        ),
        migrations.RemoveField(
            model_name='modelo111190',
            name='retenciones111',
        ),
    ]
