# Generated by Django 3.2 on 2021-08-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_auto_20210802_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo111190',
            name='base190',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelo111190',
            name='baseIRPF1T',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelo111190',
            name='baseIRPF2T',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelo111190',
            name='baseIRPF3T',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelo111190',
            name='baseIRPF4T',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelo111190',
            name='reten190',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelo111190',
            name='reten1T',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelo111190',
            name='reten2T',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelo111190',
            name='reten3T',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelo111190',
            name='reten4T',
            field=models.FloatField(default=0),
        ),
    ]
