# Generated by Django 3.2 on 2021-08-03 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_auto_20210802_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomyss',
            options={'ordering': ['mes']},
        ),
        migrations.AlterField(
            model_name='asesor',
            name='idUsuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asesor', to=settings.AUTH_USER_MODEL),
        ),
    ]
