# Generated by Django 3.2 on 2021-08-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_auto_20210803_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo111190',
            name='anyo',
            field=models.IntegerField(default=2021),
        ),
    ]
