# Generated by Django 3.2 on 2021-08-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_modelo111190_anyo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo111190',
            options={'ordering': ['-anyo']},
        ),
        migrations.AddField(
            model_name='modelo111190',
            name='fin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelo111190',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomyss',
            name='anyo',
            field=models.IntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='nomyss',
            name='fin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomyss',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nomyss',
            name='mes',
            field=models.CharField(blank=True, choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Enero', max_length=25),
        ),
    ]
