# Generated by Django 3.2 on 2021-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0013_remove_empresa_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomyss',
            name='recalculo',
            field=models.BooleanField(default=False),
        ),
    ]
