# Generated by Django 3.2 on 2021-08-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_nomyss_recalculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresaEmp', to='nucleo.empresa'),
        ),
    ]
